server.port: 8091

coffeenet:
  application-name: ExampleLogging
  profile: development
  logging:
    enabled: true
    console:
      enabled: true
    file:
      enabled: true
      file: logs/app.log
      max-history: 30
      file-name-pattern: logs/app-%d{yyyy-MM-dd}.log
      pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} %5p --- [%t] %-40.40logger{39} : %m%n%wEx'
    gelf:
      enabled: true
      server: localhost
      port: 12201
      protocol: UDP
      environment: dev
      layout: '%m %n'